sudo: false
language: node_js
node_js:
  - "node"

cache: yarn

script:
  - yarn build-lib
  - ./node_modules/.bin/ng test demo --progress false --watch=false --browsers ChromeHeadlessCustom
  - ./node_modules/.bin/ng test fab-speed-dial --progress false --watch=false --browsers ChromeHeadlessCustom
