language: node_js
node_js:
  - '12'

cache: yarn

jobs:
  include:
    - stage: test
      script:
        - yarn build-lib
        - ./node_modules/.bin/ng test fab-speed-dial --progress false --watch=false --browsers ChromeHeadlessCustom
        - ./node_modules/.bin/ng test demo --progress false --watch=false --browsers ChromeHeadlessCustom
        - yarn build-demo
        - yarn lint

    - stage: publish docs
      if: branch IN (master, develop)
      script:
        - yarn build-demo
      deploy:
        provider: pages
        skip-cleanup: true
        local-dir: dist/demo
        github-token: $GITHUB_TOKEN
        on:
          all_branches: true

    - stage: publish npm package
      if: tag is present
      script:
        - yarn build-lib
      before_deploy:
        - rm .gitignore
        - cd dist/fab-speed-dial
      deploy:
        provider: npm
        skip-cleanup: true
        email:
          secure: XWYIcUYSjTyDCR9WKraRY5g7jDBasZLbNnJGn6dh/5sqkCXBrLjhQNVz3Dt4Yf/yRBkskfIV9fGGFNXewNtH6mAqLV4IIWmA3lnQ8dMm/3gGW/cQ9EnCeUkH7mWt4EV27tCOkFpLeuCNRVwrRQhjEpGWdD9gwFR/FkFK4d/5jwzopXh0lxa0IjxWAxXnv/mIZcjlPm14VyZqZ4jzD0jlqQn4UIS32ysEbKOmI+VF2UkpMY9Ye5T6lAXPJWCkIcqrUVGk/Bjty4gq76P/hGTTiglTHuSF/7ayie+X3++PZ/hu5DAGWDzreOrmiHX8zpjeZATq0085u4jPfxN2RhKXhs4wRIaQ7dFEuKpyipLS4vlChdJQ6F6GvLjVYYL7qwfGyu+ejTuCNbCfBKrzhbvLN3TrGtBCprwDPrsfj7HkTNde+KNDbL4/hXLI9oY4f9X/eslsj8wgeRehv5O62plPTb/hAIBl3WMEe/ixNidiKlXOz2Qfl2GlKILtg4WAWEi9lHxpbAk31JlKRegK1h9eOnf3twXJ9uUv/RieuDnPVlF7ps0GFG2Ol46GfqW+fWvlwmPSuf9k+IgnTSV5Ah8wgdijMJgKJcJSaTaE9wpFmyKLzNSwn59EjvHGBlNP1H9okWQFxjbZWanOO/A+Ac7ZwZ5Nlx/7qH/FEVqsW1U5QTM=
        api_key:
          secure: jUUBPgilJhRUVvy1F39B1etpjepCdf1VvfSJ2oW4HCZ9zal/LKNOGZAaw1+GyX4ZPYlkfHmFEVhTVH9hlQI9OUD99lJ9LNhZmWYLzjJkaDWFOyx4ODre83Vfsin2/O3ov9XGMaFUO4x1CNFuO9xYA0s0xh+Le1lDdDpZ6eUI9GPHwxYEDn7TJIjf57vTadoxM0eYbYZjqVyQQulXB5pJf+5vAPEryqOJUPDTtKVDpkXgbruyqck3SsW76FSj4LTaehfO7zpdsXPsP18/y0LwdSyO3sJASU2fUMed9BAF+x/hh2CYg3h4/MdE0llMEJ9EnZMXXi4CLrYOk3Srn1t0LopIUh+tSNWn/aoA6XM7doEZwhlQqOynazKcWhgd15CHoHnMbv1gazry2NAtDhKdMlBIFqpSDg9yR2z3G0FclrBNAzGuIzC70NDF6vvjmWF7jxdM4z7XYnQj6DkfMg/eNftHNH3bJoLojiBsf7fR6T1hsxIAX7uwIJG/F1PI79z6nh2wC+10VjqZc4edA+iqeHKXqoreVed62gqYrvwedNvOcGBoghHW6nYprsxbSBoNfl9h+kXVDj02cLNnqiSdMzZ1iwCFTkQYD4BP4zvGyU2W8huIebyTv9DkaUOWEh/ZnyPd3RSLh6UwB7OsnkWIvPstDjmTUuPaReVbjl5DN44=
        on:
          tags: true
